defmodule TicketProcessor.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :title, :text, null: false
      add :description, :text, null: false
      add :status, :text, null: false, default: "open"
      add :priority, :text, null: false, default: "medium"
      add :assigned_to, {:array, :text}, default: []

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:tickets, [:title], name: "tickets_unique_title_index")
  end

  def down do
    drop_if_exists unique_index(:tickets, [:title], name: "tickets_unique_title_index")

    drop table(:tickets)
  end
end
