defmodule TicketProcessor.Repo.Migrations.AddMissingTicketFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :blocks_resolution, :text, null: false, default: "none"
      add :depends_on_person, :text
    end

    create table(:ticket_dependencies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :dependency_type, :text, null: false, default: "blocks"
      add :dependency_data, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :blocking_ticket_id,
          references(:tickets,
            column: :id,
            name: "ticket_dependencies_blocking_ticket_id_fkey",
            type: :uuid
          ),
          null: false

      add :dependent_ticket_id,
          references(:tickets,
            column: :id,
            name: "ticket_dependencies_dependent_ticket_id_fkey",
            type: :uuid
          ),
          null: false
    end
  end

  def down do
    drop constraint(:ticket_dependencies, "ticket_dependencies_blocking_ticket_id_fkey")

    drop constraint(:ticket_dependencies, "ticket_dependencies_dependent_ticket_id_fkey")

    drop table(:ticket_dependencies)

    alter table(:tickets) do
      remove :depends_on_person
      remove :blocks_resolution
    end
  end
end
